workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' #https://docs.gitlab.com/ee/ci/yaml/README.html#common-if-clauses-for-rules
    - if: '$CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api$/'
    - if: '$RUN_COMPONENT == "gitops"'

image:
  name: ${CAF_ROVER_VERSION}

variables:
  MSI_ID: ${CAF_MSI_ID_LEVEL_1}
  TF_VAR_tfstate_subscription_id: ${TF_VAR_tfstate_subscription_id}
  target_subscription: ${target_subscription}
  ROVER_RUNNER: "true"
  LZ_BRANCH: ${LZ_BRANCH}
  caf_env: ${CAF_ENV} #"contoso-sandpit"
  ARM_USE_MSI: "true"
  TFSTATE_FILENAME: caf_gitops_aks_secure_baseline_v2.tfstate
  TF_PARALLELISM: 30
  LANDING_ZONE_LEVEL: level1
  LANDING_ZONE_NAME: caf_solution/add-ons/aks_secure_baseline_v2
  LANDING_ZONE_CONFIG_NAME: gitops/aks-secure-baseline_v2
  LANDING_ZONE_PATH: ${CI_PROJECT_DIR}/landingzones/${LANDING_ZONE_NAME}
  LANDING_ZONE_CONFIG_PATH: ${CI_PROJECT_DIR}/contoso/${LANDING_ZONE_LEVEL}/${LANDING_ZONE_CONFIG_NAME}
  TFPLAN_JSON_PATH: ${CI_PROJECT_DIR}/.terraform.cache/tfstates/${LANDING_ZONE_LEVEL}/tfstate/${LANDING_ZONE_CONFIG_NAME}.tfplan.json

before_script:
  - git config --global http.postBuffer 1048576000
  - git clone --branch ${LZ_BRANCH} ${LZ_REPO_URL} /${CI_PROJECT_DIR}/landingzones
  - cd ${CI_PROJECT_DIR}
  - ls -lsa
  - az login --identity

stages:
  - validate
  - plan
  - apply
  - destroy

# cache:
#   paths:
#     - ${CI_PROJECT_DIR}/.terraform.cache/


gitop_aks_secure_baseline_plan:
  stage: plan
  environment:
    name: caf_platform
  script:
    - /tf/rover/rover.sh
      -lz ${LANDING_ZONE_PATH}
      -tfstate ${TFSTATE_FILENAME}
      -var-folder ${LANDING_ZONE_CONFIG_PATH}
      -parallelism=${TF_PARALLELISM}
      -level ${LANDING_ZONE_LEVEL}
      -tfstate_subscription_id ${TF_VAR_tfstate_subscription_id}
      -target_subscription ${target_subscription}
      -a plan
      -env ${caf_env}
  tags:
    - CAF_LEVEL_1

  artifacts:
    name: plan
    expire_in: never
    reports:
      terraform: ${TFPLAN_JSON_PATH}

gitop_aks_secure_baseline_apply:
  stage: apply
  environment:
    name: caf_platform
  dependencies:
    - gitop_aks_secure_baseline_plan
  script:
    - /tf/rover/rover.sh
      -lz ${LANDING_ZONE_PATH}
      -tfstate ${TFSTATE_FILENAME}
      -var-folder ${LANDING_ZONE_CONFIG_PATH}
      -parallelism=${TF_PARALLELISM}
      -level ${LANDING_ZONE_LEVEL}
      -tfstate_subscription_id ${TF_VAR_tfstate_subscription_id}
      -target_subscription ${target_subscription}
      -a apply
      -env ${caf_env}
  tags:
    - CAF_LEVEL_1

gitop_aks_secure_baseline_destroy:
  stage: destroy
  environment:
    name: caf_platform
    action: stop
  script:
    - /tf/rover/rover.sh
      -lz ${LANDING_ZONE_PATH}
      -tfstate ${TFSTATE_FILENAME}
      -var-folder ${LANDING_ZONE_CONFIG_PATH}
      -parallelism=${TF_PARALLELISM}
      -level ${LANDING_ZONE_LEVEL}
      -tfstate_subscription_id ${TF_VAR_tfstate_subscription_id}
      -target_subscription ${target_subscription}
      -a destroy
      -env ${caf_env}
      -auto-approve

  tags:
    - CAF_LEVEL_1

  when: manual
